#!/bin/bash
#My First script

make
./Parser test1.txt
./Parser test2.txt
./Parser test3.txt
./Parser test4.txt

./Parser illegaltest1.txt
./Parser illegaltest2.txt
./Parser illegaltest3.txt
./Parser illegaltest4.txt
make clean
